# MkDocs static site generator configuration file.
#
# For more information, visit https://www.mkdocs.org/user-guide/configuration/.

copyright: Copyright &copy; 2021 James Mullinix
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mullinix
    - icon: fontawesome/solid/envelope
      link: mailto://james.mullinix@gmail.com
extra_css:
  - css/style.css
extra_javascript:
  - https://unpkg.com/mermaid@8.9.3/dist/mermaid.min.js
  - js/index.js
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - footnotes
  - meta
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true
nav:
  - Home: index.md
  - User Guide: src/user/index.md
  - API Reference: src/reference/index.md
  - Developer Guide: src/developer/index.md
plugins:
  - mkdocstrings
  - search
repo_name: clean-jdr
repo_url: https://github.com/mullinix/clean-jdr
site_author: James Mullinix
site_description: |
  Clean output files (.jdr) from wire sniffing.
site_name: clean-jdr
site_url: https://mullinix.github.io/clean-jdr
theme:
  featues:
    - navigation.tabs
  name: material
  palette:
    accent: cyan
    primary: teal
