# GitHub Actions workflow file.
#
# For more information, visit
# https://docs.github.com/actions/learn-github-actions.

name: release

# Trigger workflow on SemVer compatible tags.
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    name: Get Git tag and make GitHub release
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.extract_tag.outputs.tag }}
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Extract tag
        id: extract_tag
        shell: bash
        run: echo "##[set-output name=tag;]$(echo ${GITHUB_REF#refs/tags/})"
      - name: Checkout code repository
        uses: actions/checkout@v2
      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: clean-jdr ${{ steps.extract_tag.outputs.tag }}
          body: >-
            See the
            [changelog](https://github.com/mullinix/clean-jdr/blob/${{
            steps.extract_tag.outputs.tag }}/CHANGELOG.md) for more information.

  package:
    name: Build and publish Python package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v2
      - name: Install Python interpreter
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip poetry setuptools wheel
          poetry install --no-dev
      - name: Build Python package
        run: poetry build
      - name: Upload package to GitHub release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: >-
            dist/clean_jdr-${{ steps.extract_tag.outputs.tag
            }}-py3-none-any.whl
          asset_name: >-
            clean_jdr-${{ steps.extract_tag.outputs.tag
            }}-py3-none-any.whl
          asset_content_type: application/octet-stream
      # Use PyPI publish action over Poetry publish to prevent PyPI password
      # from being printed in CI logs.
      - name: Upload package to PyPI
        uses: pypa/gh-action-pypi-publish@v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}
